version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      - .:/app
    env_file: docker/development/.env
    command: puma -C config/puma.rb
    # environment:
    #   - UID
    #   - GID
    ports:
      - 3000:3000
    # stdin_open: true
    # tty: true
